# Chapter 4 - Linear Algebra

In [1]:
# 3 dimensional vector
import numpy as np
v = np.array([4, 1, 2])
print(v)

[4 1 2]


In [2]:
# 5 dimensional vector
v = np.array([6, 1, 5, 8, 3])
print(v)

[6 1 5 8 3]


In [4]:
# vector addition
v = np.array([3,2])
w = np.array([2,-1])
# sum the vectors
v_plus_w = v + w
# display summed vector
print(v_plus_w) # [5, 1]

[5 1]


In [6]:
# scalar
v = np.array([3,1])
# scale the vector
scaled_v = 2.0 * v
# display scaled vector
print(scaled_v) # [6 2]

[6. 2.]


In [7]:
# compose basis matrix with i-hat and j-hat
basis = np.array(
[[3, 0],
[0, 2]]
)
# declare vector v
v = np.array([1,1])
# create new vector
# by transforming v with dot product
new_v = basis.dot(v)
print(new_v) # [3, 2]

[3 2]


In [8]:
# Declare i-hat and j-hat
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])
# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = np.array([i_hat, j_hat]).transpose()
# declare vector v
v = np.array([1,1])
# create new vector
# by transforming v with dot product
new_v = basis.dot(v)
print(new_v) # [2, 3]

[2 3]


In [11]:
# Declare i-hat and j-hat
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])
# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = np.array([i_hat, j_hat]).transpose()
# declare vector v 0
v = np.array([2,1])
# create new vector
# by transforming v with dot product
new_v = basis.dot(v)
print(new_v) # [4 3]

[4 3]


In [12]:
from numpy import array
# Declare i-hat and j-hat
i_hat = array([2, 3])
j_hat = array([2, -1])
# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()
# declare vector v 0
v = array([2,1])
# create new vector
# by transforming v with dot product
new_v = basis.dot(v)
print(new_v) # [6, 5]

[6 5]


In [13]:
# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()
# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()
# Combine Transformations
combined = transform2 @ transform1
# Test
print("COMBINED MATRIX:\n {}".format(combined))
v = array([1, 2])
print(combined.dot(v)) # [-1 1]

COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


In [14]:
rotated = transform1.dot(v)
sheered = transform2.dot(rotated)
print(sheered) # [-1 1]

[-1  1]


In [15]:
# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()
# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()
# Combine Transformations, apply sheer first and then rotation
combined = transform1 @ transform2
# Test
print("COMBINED MATRIX:\n {}".format(combined))
v = array([1, 2])
print(combined.dot(v)) # [-2 3]

COMBINED MATRIX:
 [[ 0 -1]
 [ 1  1]]
[-2  3]


In [17]:
from numpy.linalg import det
from numpy import array
i_hat = array([3, 0])
j_hat = array([0, 2])
basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)
print(determinant) # prints 6.0

6.0


In [18]:
from numpy.linalg import det
from numpy import array
i_hat = array([1, 0])
j_hat = array([1, 1])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints 1.0

1.0


In [19]:
from numpy.linalg import det
from numpy import array
i_hat = array([-2, 1])
j_hat = array([1, 2])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints -5.0

-5.000000000000001


In [20]:
i_hat = array([-2, 1])
j_hat = array([3, -1.5])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints 0.0

0.0


In [21]:
from sympy import *
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = Matrix([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])
# dot product between A and its inverse
# will produce identity function
inverse = A.inv()
identity = inverse * A
# prints Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
print("INVERSE: {}".format(inverse))
# prints Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print("IDENTITY: {}".format(identity))

INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [22]:
from numpy import array
from numpy.linalg import inv
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = array([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])
B = array([
44,
56,
72
])
X = inv(A).dot(B)
print(X) # [ 2. 34. -8.]

[ 2. 34. -8.]


In [23]:
from sympy import *
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = Matrix([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
    ])
B = Matrix([
44,
56,
72
])
X = A.inv() * B
print(X) # Matrix([[2], [34], [-8]])

Matrix([[2], [34], [-8]])


In [24]:
# eigenvectors